### ISSUE TITLE
cli - deploy.js - uses deprecated ethers method

### ISSUE THREAD

**Issue by purestaketdb** [ChainSafe/chainbridge-deploy#37] opened 2020-12-15 20:51 UTC
In cb-sol-cli/cmd/deploy.js these two statements cause an error during contract deploy:

Gas Limit:   ${ethers.utils.bigNumberify(args.gasLimit)}
Gas Price:   ${ethers.utils.bigNumberify(args.gasPrice)}

Error: `e: TypeError: ethers.utils.bigNumberify is not a function`

In the current 5.x.x ethers versions utils.bigNumberify() has been replaced by BigNumber.from().

Reviewable in the v4 to v5 update guide. 
https://github.com/ethers-io/ethers.js/blob/efeeda5e5c3b22f0c211783a635941dc8035ae25/docs/v5/migration/ethers-v4/README.md

Swapped the methods and contracts deployed as expected.

**Comment by P1sar** [comment] 2021-04-05 09:22
Closing this as duplicate of #39

**Closed by P1sar** 2021-04-05 09:22 UTC
